"""Validated chat-domain values and tokenizer-agnostic rendering."""

from scratch_llm.chat.conversation import (
    CHAT_SCHEMA_VERSION,
    AssistantContent,
    AssistantMessage,
    AssistantPart,
    Conversation,
    ConversationValidationError,
    Message,
    PythonOutputPart,
    PythonPart,
    SystemMessage,
    TextPart,
    UserMessage,
    conversation_to_dict,
    conversation_to_json,
    parse_conversation,
    read_conversations,
    write_conversation_jsonl,
)
from scratch_llm.chat.rendering import (
    CHAT_RENDERER_ID,
    IGNORE_INDEX,
    ChatRenderingError,
    CompletionPrompt,
    RenderedConversation,
    ShiftedSFTSequence,
    render_completion_prompt,
    render_conversation,
    shift_sft_targets,
)
from scratch_llm.chat.engine import (
    ChatEngine,
    ChatEngineError,
    ChatState,
    ChatStatus,
    TokenEvent,
    TokenEventType,
    close_token_stream,
)

__all__ = [
    "CHAT_RENDERER_ID",
    "CHAT_SCHEMA_VERSION",
    "IGNORE_INDEX",
    "AssistantContent",
    "AssistantMessage",
    "AssistantPart",
    "ChatEngine",
    "ChatEngineError",
    "ChatRenderingError",
    "ChatState",
    "ChatStatus",
    "CompletionPrompt",
    "Conversation",
    "ConversationValidationError",
    "Message",
    "PythonOutputPart",
    "PythonPart",
    "RenderedConversation",
    "ShiftedSFTSequence",
    "SystemMessage",
    "TextPart",
    "TokenEvent",
    "TokenEventType",
    "UserMessage",
    "conversation_to_dict",
    "conversation_to_json",
    "close_token_stream",
    "parse_conversation",
    "read_conversations",
    "render_completion_prompt",
    "render_conversation",
    "shift_sft_targets",
    "write_conversation_jsonl",
]
