"""Validated chat-domain values and tokenizer-agnostic rendering."""

from scratch_llm.chat.conversation import (
    CHAT_SCHEMA_VERSION,
    AssistantContent,
    AssistantMessage,
    AssistantPart,
    Conversation,
    ConversationValidationError,
    Message,
    PythonOutputPart,
    PythonPart,
    SystemMessage,
    TextPart,
    UserMessage,
    parse_conversation,
    read_conversations,
)
from scratch_llm.chat.rendering import (
    CHAT_RENDERER_ID,
    IGNORE_INDEX,
    ChatRenderingError,
    CompletionPrompt,
    RenderedConversation,
    ShiftedSFTSequence,
    render_completion_prompt,
    render_conversation,
    shift_sft_targets,
)
from scratch_llm.chat.datasets import (
    NANOCHAT_SFT_REFERENCE_COMMIT,
    SFTConversationDataset,
    SFTConversationExample,
    SFTDatasetError,
    SFTDatasetRowError,
    get_sft_dataset_spec,
    normalize_gsm8k_row,
    normalize_mmlu_row,
    normalize_smoltalk_row,
    parse_gsm8k_answer_parts,
)
from scratch_llm.chat.hub import (
    CachedHubParquetDataset,
    HubDatasetSpec,
    HubParquetCacheError,
    HubParquetDiscoveryError,
    prepare_hub_parquet_cache,
    publish_local_parquet_cache,
)


__all__ = [
    "CHAT_RENDERER_ID",
    "CHAT_SCHEMA_VERSION",
    "IGNORE_INDEX",
    "AssistantContent",
    "AssistantMessage",
    "AssistantPart",
    "CachedHubParquetDataset",
    "ChatRenderingError",
    "CompletionPrompt",
    "Conversation",
    "ConversationValidationError",
    "HubDatasetSpec",
    "HubParquetCacheError",
    "HubParquetDiscoveryError",
    "Message",
    "NANOCHAT_SFT_REFERENCE_COMMIT",
    "PythonOutputPart",
    "PythonPart",
    "RenderedConversation",
    "SFTConversationDataset",
    "SFTConversationExample",
    "SFTDatasetError",
    "SFTDatasetRowError",
    "ShiftedSFTSequence",
    "SystemMessage",
    "TextPart",
    "UserMessage",
    "parse_conversation",
    "get_sft_dataset_spec",
    "normalize_gsm8k_row",
    "normalize_mmlu_row",
    "normalize_smoltalk_row",
    "parse_gsm8k_answer_parts",
    "prepare_hub_parquet_cache",
    "publish_local_parquet_cache",
    "read_conversations",
    "render_completion_prompt",
    "render_conversation",
    "shift_sft_targets",
]
